CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `first_name` varchar(255) NOT NULL,
  `middle_name` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) NOT NULL,
  `password` varchar(255) DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `role_id` int NOT NULL,
  `password_reset_required` tinyint(1) DEFAULT '0',
  `sf_user_id` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `username` varchar(255) NOT NULL,
  `ceo3_sf_user_id` varchar(255) DEFAULT NULL,
  `hrbp_sf_user_id` varchar(255) DEFAULT NULL,
  `gross_salary` decimal(10,2) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `ms_user_id` varchar(255) DEFAULT NULL,
  `profile_picture` varchar(255) DEFAULT NULL,
  `banner_picture` varchar(255) DEFAULT NULL,
  `previous_passwords` json DEFAULT NULL,
  `password_last_changed` datetime DEFAULT NULL,
  `last_login` datetime DEFAULT NULL,
  `is_blocked` tinyint(1) DEFAULT '0',
  `block_remark` varchar(255) DEFAULT NULL,
  `is_sso` tinyint(1) DEFAULT '0',
  `date_time_format_id` int DEFAULT NULL,
  `is_date_format_preference_set` tinyint(1) DEFAULT '0',
  `otp` varchar(255) DEFAULT NULL,
  `otp_time` datetime DEFAULT NULL,
  `access_given_on` datetime DEFAULT NULL,
  `access_given_by` int DEFAULT NULL,
  `ip_address` varchar(255) DEFAULT NULL,
  `sf_data` json DEFAULT NULL,
  `wishes` json DEFAULT NULL,
  `id_card_issued_at` datetime DEFAULT NULL,
  `id_card_expired_at` datetime DEFAULT NULL,
  `feed_last_read` datetime DEFAULT NULL,
  `outage_last_read` datetime DEFAULT NULL,
  `news_last_read` datetime DEFAULT NULL,
  `joining_date_visibility` enum('everyone','only_me') DEFAULT 'everyone',
  `birthday_visibility` enum('everyone','only_me') DEFAULT 'everyone',
  `phone_visibility` enum('everyone','only_me') NOT NULL DEFAULT 'everyone',
  `saved_posts` json DEFAULT NULL,
  `failed_login_attempts` int NOT NULL DEFAULT '0',
  `is_login_blocked` tinyint(1) DEFAULT '0',
  `is_horizon_alert_editor` tinyint(1) DEFAULT '0',
  `is_horizon_alert_admin` tinyint(1) DEFAULT '0',
  `is_horizon_alert_executive` tinyint(1) DEFAULT '0',
  `is_proxy_access_allowed` tinyint(1) DEFAULT '0',
  `proxy_access_filters` json DEFAULT NULL,
  `is_learning_member` tinyint(1) DEFAULT '0',
  `is_payment_team_member` tinyint(1) DEFAULT '0',
  `is_org_vibe_allowed` tinyint(1) DEFAULT '0',
  `is_span_vibe_allowed` tinyint(1) DEFAULT '0',
  `span_vibe_filters` json DEFAULT NULL,
  `login_blocked_at` datetime DEFAULT NULL,
  `profile_completion_status` json DEFAULT NULL,
  `widget_settings` json DEFAULT NULL,
  `biography` text,
  `linkedin_url` varchar(255) DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `sf_data_managerId` varchar(100) GENERATED ALWAYS AS (json_unquote(json_extract(`sf_data`,_utf8mb4'$.managerId'))) STORED,
  `sf_data_jobGrade` varchar(100) GENERATED ALWAYS AS (json_unquote(json_extract(`sf_data`,_utf8mb4'$.jobGrade'))) STORED,
  `sf_data_employeeCode` varchar(100) GENERATED ALWAYS AS (json_unquote(json_extract(`sf_data`,_utf8mb4'$.employeeCode'))) STORED,
  `sf_data_employmentType` varchar(100) GENERATED ALWAYS AS (json_unquote(json_extract(`sf_data`,_utf8mb4'$.employmentType'))) STORED,
  `sf_data_countryOfCompany` varchar(100) GENERATED ALWAYS AS (json_unquote(json_extract(`sf_data`,_utf8mb4'$.countryOfCompany'))) STORED,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_username_unique` (`username`),
  KEY `is_active` (`is_active`),
  KEY `is_blocked` (`is_blocked`),
  KEY `role_id` (`role_id`),
  KEY `date_time_format_id` (`date_time_format_id`),
  KEY `access_given_by` (`access_given_by`),
  KEY `is_sso` (`is_sso`),
  KEY `users_email_index` (`email`),
  KEY `users_sf_user_id_index` (`sf_user_id`),
  KEY `users_ms_user_id_index` (`ms_user_id`),
  KEY `users_is_span_vibe_allowed_index` (`is_span_vibe_allowed`),
  KEY `idx_users_is_learning_member` (`is_learning_member`),
  KEY `users_is_proxy_access_allowed` (`is_proxy_access_allowed`),
  KEY `idx_sf_data_managerId` (`sf_data_managerId`),
  KEY `idx_sf_data_jobGrade` (`sf_data_jobGrade`),
  KEY `idx_sf_data_employeeCode` (`sf_data_employeeCode`),
  KEY `idx_sf_data_employmentType` (`sf_data_employmentType`),
  KEY `idx_sf_data_countryOfCompany` (`sf_data_countryOfCompany`),
  KEY `users_is_horizon_alert_editor` (`is_horizon_alert_editor`),
  KEY `users_is_horizon_alert_admin` (`is_horizon_alert_admin`),
  KEY `users_is_horizon_alert_executive` (`is_horizon_alert_executive`),
  CONSTRAINT `fk_access_given_by_user`
    FOREIGN KEY (`access_given_by`)
    REFERENCES `users` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
